version: '3.8'

services:
  postgres:
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    image: postgres:15.2

  app:
    build: ./
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - SPRING_DATA_SOURCE=jdbc:postgresql://postgres/postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

volumes:
  postgres-data: