INSERT INTO NEWS_TOPICS
VALUES (1, 'Politics');
INSERT INTO NEWS_TOPICS
VALUES (2, 'Business');
INSERT INTO NEWS_TOPICS
VALUES (3, 'Sports');
INSERT INTO NEWS_TOPICS
VALUES (4, 'Entertainment');
INSERT INTO NEWS_TOPICS
VALUES (5, 'Technology');
INSERT INTO NEWS_TOPICS
VALUES (6, 'Technology');

INSERT INTO NEWS_SOURCE
VALUES (1, 'The New York Times ');
INSERT INTO NEWS_SOURCE
VALUES (2, 'QAZAQSTAN');
INSERT INTO NEWS_SOURCE
VALUES (3, 'HABAR');
INSERT INTO NEWS_SOURCE
VALUES (4, 'KTK');


INSERT INTO NEWS(SOURCE_ID, CONTENT, TITLE)
VALUES(1, 'fffffffffffff', 'title');


